AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWSSamples::Devtools::Devinstance resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers.testEntrypoint
      Runtime: nodejs12.x
      CodeUri: ./
      Environment:
        Variables:
          HY_OVERRIDE_CREDENTIALS:
          HY_ACCESS_KEY_ID:
          HY_SECRET_ACCESS_KEY:

  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers.entrypoint
      Runtime: nodejs12.x
      CodeUri: ./
      Environment:
        Variables:
          HY_OVERRIDE_CREDENTIALS:
          HY_ACCESS_KEY_ID:
          HY_SECRET_ACCESS_KEY:
