AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWSSamples::EFSEncrypt::Hook resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 1024

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.awssamples.efsencrypt.hook.HookHandlerWrapper::handleRequest
      Runtime: java11
      CodeUri: ./target/awssamples-efsencrypt-hook-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.awssamples.efsencrypt.hook.HookHandlerWrapper::testEntrypoint
      Runtime: java11
      CodeUri: ./target/awssamples-efsencrypt-hook-handler-1.0-SNAPSHOT.jar

