AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the s3-versioning-enabled sample Lambda function.

Globals:
  Function:
    Timeout: 10
    MemorySize: 256

Resources:
  S3VersioningEnabledFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: ruby3.2
      CodeUri: .
