# Configuration file for pre-commit; reference: https://pre-commit.com/

fail_fast: true

repos:

  - repo: https://github.com/awslabs/git-secrets
    rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38
    hooks:
      - id: git-secrets
        entry: git-secrets --scan
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*

      - id: check-merge-conflict
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*

      - id: check-yaml
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*
        # Exclude example AWS CloudFormation templates in the examples
        # directory.
        exclude: ^hooks\/java-hooks\/ec2-instance-types\/.*examples/.*\.(template|yaml|yml)$

      - id: detect-private-key
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*

      - id: end-of-file-fixer
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*
        exclude: ^hooks\/java-hooks\/ec2-instance-types\/.*docs/.*\.md$

      - id: mixed-line-ending
        args:
          - --fix=lf
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*

      - id: pretty-format-json
        args:
          - --autofix
          - --indent=4
          - --no-sort-keys
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*

      - id: trailing-whitespace
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*

  - repo: local
    hooks:
      - id: mvn-clean-verify-local
        name: mvn-clean-verify-local
        entry: bash -c "cd hooks/java-hooks/ec2-instance-types && mvn clean verify"
        always_run: true
        language: system
        pass_filenames: false

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.72.2
    hooks:
      - id: cfn-python-lint
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*examples/.*\.(template|json|yaml|yml)$

  - repo: https://github.com/aws-cloudformation/rain
    rev: v1.2.0
    hooks:
      - id: cfn-format
        files: ^hooks\/java-hooks\/ec2-instance-types\/.*examples/.*\.(template|json|yaml|yml)$
