AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWSSamples::S3BucketEncrypt::Hook resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: awssamples_s3bucketencrypt_hook.handlers.hook
      Runtime: python3.9
      CodeUri: build/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: awssamples_s3bucketencrypt_hook.handlers.test_entrypoint
      Runtime: python3.9
      CodeUri: build/

